import Component from '@glimmer/component';

export default class StructuralRoutesRyanPortfolioIndexPageComponent extends Component {
  githubIcon = 'github-alt';
  githubPrefix = 'fab';
  githubSize = '2x';
  linkedinIcon = 'linkedin';
  linkedinPrefix = 'fab';
  linkedinSize = '2x';
  avatarImage = '/assets/images/RyanHeadShot.png';
  aboutMeRoute = 'ryan.about';
  portfolioRoute = 'ryan.portfolio';
  blogRoute = 'ryan.blog';
  resumeRoute = 'ryan.resume';
  contactRoute = 'ryan.contact';
  headerName = 'Ryan Roderick';
  headerTitle = 'Web Developer';
  headerButtonLabel = 'Hire Me!';
  headerButtonRoute = 'ryan.contact';
  projectOneProjectTitle = 'Project 1';
  projectOneProjectDescription = 'Description Goes Here!!';
  projectOneBlockOneImage = '/assets/images/RyanHeadShot.png';
  projectOneIconOne = '';
  projectOneIconTwo = '';
  projectOneIconThree = '';
  projectOneBlockTwoLabel = 'Stack';
  projectOneBlockThreeTextOne = '1 - This is where a short description of Challenges will go';
  projectOneBlockThreeTextTwo = '2 - This is where a short description of Challenges will go';
  projectOneBlockThreeTextThree = '3 - This is where a short description of Challenges will go';
  projectOneBlockThreeLabel = 'Challenges';
  projectOneBlockFourTextOne = '1 - This is where a short description of solutions goes';
  projectOneBlockFourTextTwo = '2 - This is where a short description of solutions goes';
  projectOneBlockFourTextThree = '3 - This is where a short description of solutions goes';
  projectOneBlockFourTextFour = '4 - This is where a short description of solutions goes';
  projectOneBlockFourTextFive = '5 - This is where a short description of solutions goes';
  projectOneBlockFourLabel = 'Solutions';
  projectOneBlockFiveText = 'Repo';
  projectOneBlockFiveLabel = 'See the Code';
  projectOneBlockSixText = 'Live Site';
  projectOneBlockSixLabel = 'See it in Action';
}