import Component from '@glimmer/component';

export default class StructuralRoutesRyanBlogEmberMobileMenuComponent extends Component {
  githubUrl = 'https://github.com/RpRoderick';
  githubIcon = 'github-alt';
  githubPrefix = 'fab';
  githubSize = '2x';
  linkedInUrl = 'https://www.linkedin.com/in/ryan-roderick';
  linkedinIcon = 'linkedin';
  linkedinPrefix = 'fab';
  linkedinSize = '2x';
  avatarImage = 'https://designmonster.s3.us-east-2.amazonaws.com/headshotryan.png';
  aboutMeRoute = 'ryan.about';
  portfolioRoute = 'ryan.portfolio';
  blogRoute = 'ryan.blog';
  resumeRoute = 'ryan.resume';
  contactRoute = 'contact';
  sideBarMenu = true;
  headerNameFirst = 'RYAN';
  headerNameLast = 'Roderick';
  headerButtonLabel = 'Hire Me!';
  codePathOne = '<Structural::Ui::Navigation::Mobile>';
  codeOne = '{{outlet}}';
  codePathTwo = '<Structural::Ui::Navigation::Mobile>';
  codeTwo = '* master';
  codeTwoOutlet = '{{outlet}}';
  codePathThree = '<MobileMenuWrapper as | mmw | >';
  codePathFour = '< mmw.MobileMenu as | mm | >';
  codePathFive = '<mm.LinkTo @route="index">Home</mm.LinkTo>';
  codePathSix = '</mmw.MobileMenu>';
  codePathSeven = '<mmw.Content>';
  codePathEight = '<mmw.Toggle>Menu</mmw.Toggle>';
  codeEightOutlet = '{{yield}}';
  codePathNine = '</mmw.Content>';
  codePathTen = '</MobileMenuWrapper>';
  codePathEleven = '{{#if (or (media \'is small \' )  (media \'isMedium \' ))}}';
  codePathTwelve = '<Dynamic::Ui::Navigation::Mobile>';
  codePathThirteen = '</Dynamic::Ui::Navigation::Mobile>';
  codePathFourteen = '{{else}}';
  codePathFifteen = '{{/if}}';
  codeThree = '* master';
}
